### ISSUE TITLE
Routes pushed by the server are not added when using eduVPN client or NetworkManager to connect

### ISSUE THREAD

**Issue by martijnkruiten** [eduvpn/python-eduvpn-client#407] opened 2021-08-27 09:41 UTC
# Installation

https://python-eduvpn-client.readthedocs.io/en/master/installation.html#fedora-and-centos

# Version

2.1.0-1.fc34

# OS/Distribution

Fedora 34

# Logs

EduVPN:

```
2021-08-27 11:14:40,165 - MainThread - INFO - eduvpn.app - app.py:139 - interface transitioning: <ConnectionStatus server=<InstituteAccessServer 'SURF BV'>, validity=<eduvpn.crypto.Validity object at 0x7fe24c0adfd0>> -> activate_connection
2021-08-27 11:14:40,165 - MainThread - INFO - eduvpn.app - app.py:120 - network transitioning: <DisconnectedState> -> reconnect
2021-08-27 11:14:40,165 - MainThread - INFO - eduvpn.nm - nm.py:162 - activate_connection uuid: fa728f67-49b5-4671-acf2-b4303789f52b connection: <NM.RemoteConnection object at 0x7fe24c04b480 (NMRemoteConnection at 0x55d63e5c7190)>
2021-08-27 11:14:40,168 - MainThread - INFO - eduvpn.app - app.py:131 - network transitioned: reconnect -> <ConnectingState>
2021-08-27 11:14:40,173 - MainThread - INFO - eduvpn.app - app.py:150 - interface transitioned: activate_connection -> <ConnectionStatus server=<InstituteAccessServer 'SURF BV'>, validity=<eduvpn.crypto.Validity object at 0x7fe24c0adfd0>>
2021-08-27 11:14:40,207 - MainThread - INFO - eduvpn.nm - nm.py:177 - activate_connection_async result: <NM.VpnConnection object at 0x7fe24c04bb00 (NMVpnConnection at 0x55d63e7513f0)>
2021-08-27 11:14:40,208 - MainThread - INFO - eduvpn.app - app.py:120 - network transitioning: <ConnectingState> -> set_unknown
2021-08-27 11:14:40,209 - MainThread - INFO - eduvpn.app - app.py:139 - interface transitioning: <ConnectionStatus server=<InstituteAccessServer 'SURF BV'>, validity=<eduvpn.crypto.Validity object at 0x7fe24c0adfd0>> -> deactivate_connection
2021-08-27 11:14:40,209 - MainThread - INFO - eduvpn.app - app.py:120 - network transitioning: <UnknownState> -> disconnect
2021-08-27 11:14:40,210 - MainThread - ERROR - eduvpn.app - app.py:127 - invalid network state transition: <UnknownState> -> disconnect
2021-08-27 11:14:40,211 - MainThread - INFO - eduvpn.app - app.py:150 - interface transitioned: deactivate_connection -> <ConnectionStatus server=<InstituteAccessServer 'SURF BV'>, validity=<eduvpn.crypto.Validity object at 0x7fe24c0adfd0>>
2021-08-27 11:14:40,212 - MainThread - INFO - eduvpn.app - app.py:131 - network transitioned: set_unknown -> <UnknownState>
2021-08-27 11:14:40,220 - MainThread - INFO - eduvpn.app - app.py:120 - network transitioning: <UnknownState> -> set_error
2021-08-27 11:14:40,221 - MainThread - INFO - eduvpn.app - app.py:131 - network transitioned: set_error -> <ConnectionErrorState error=None>
2021-08-27 11:14:40,224 - MainThread - INFO - eduvpn.app - app.py:120 - network transitioning: <ConnectionErrorState error=None> -> set_connecting
2021-08-27 11:14:40,225 - MainThread - INFO - eduvpn.app - app.py:139 - interface transitioning: <ConnectionStatus server=<InstituteAccessServer 'SURF BV'>, validity=<eduvpn.crypto.Validity object at 0x7fe24c0adfd0>> -> activate_connection
2021-08-27 11:14:40,226 - MainThread - INFO - eduvpn.app - app.py:120 - network transitioning: <ConnectingState> -> reconnect
2021-08-27 11:14:40,226 - MainThread - ERROR - eduvpn.app - app.py:127 - invalid network state transition: <ConnectingState> -> reconnect
2021-08-27 11:14:40,227 - MainThread - INFO - eduvpn.app - app.py:150 - interface transitioned: activate_connection -> <ConnectionStatus server=<InstituteAccessServer 'SURF BV'>, validity=<eduvpn.crypto.Validity object at 0x7fe24c0adfd0>>
2021-08-27 11:14:40,227 - MainThread - INFO - eduvpn.app - app.py:131 - network transitioned: set_connecting -> <ConnectingState>
2021-08-27 11:14:40,367 - MainThread - INFO - eduvpn.app - app.py:120 - network transitioning: <ConnectingState> -> set_connecting
2021-08-27 11:14:40,369 - MainThread - INFO - eduvpn.app - app.py:131 - network transitioned: set_connecting -> <ConnectingState>
2021-08-27 11:14:40,413 - MainThread - INFO - eduvpn.app - app.py:120 - network transitioning: <ConnectingState> -> set_connected
2021-08-27 11:14:40,414 - MainThread - INFO - eduvpn.app - app.py:131 - network transitioned: set_connected -> <ConnectedState>
```

Journal (NetworkManager and nm-openvpn):

```
Aug 27 11:14:40 fedora34 NetworkManager[1314]: <info>  [1630055680.2046] audit: op="connection-activate" uuid="fa728f67-49b5-4671-acf2-b4303789f52b" name="eduVPN" pid=277109 uid=1000 result="success"
Aug 27 11:14:40 fedora34 NetworkManager[1314]: <info>  [1630055680.2114] vpn-connection[0x5562c6026730,fa728f67-49b5-4671-acf2-b4303789f52b,"eduVPN",0]: Started the VPN service, PID 277306
Aug 27 11:14:40 fedora34 NetworkManager[1314]: <info>  [1630055680.2203] vpn-connection[0x5562c6026730,fa728f67-49b5-4671-acf2-b4303789f52b,"eduVPN",0]: Saw the service appear; activating connection
Aug 27 11:14:40 fedora34 NetworkManager[1314]: <info>  [1630055680.2311] vpn-connection[0x5562c6026730,fa728f67-49b5-4671-acf2-b4303789f52b,"eduVPN",0]: VPN plugin: state changed: starting (3)
Aug 27 11:14:40 fedora34 NetworkManager[1314]: <info>  [1630055680.2312] vpn-connection[0x5562c6026730,fa728f67-49b5-4671-acf2-b4303789f52b,"eduVPN",0]: VPN connection: (ConnectInteractive) reply received
Aug 27 11:14:40 fedora34 nm-openvpn[277312]: OpenVPN 2.5.3 x86_64-redhat-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Jun 18 2021
Aug 27 11:14:40 fedora34 nm-openvpn[277312]: library versions: OpenSSL 1.1.1k  FIPS 25 Mar 2021, LZO 2.10
Aug 27 11:14:40 fedora34 nm-openvpn[277312]: NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Aug 27 11:14:40 fedora34 nm-openvpn[277312]: TCP/UDP: Preserving recently used remote address: [AF_INET6][REDACTED]:1194
Aug 27 11:14:40 fedora34 nm-openvpn[277312]: UDP link local: (not bound)
Aug 27 11:14:40 fedora34 nm-openvpn[277312]: UDP link remote: [AF_INET6][REDACTED]:1194
Aug 27 11:14:40 fedora34 nm-openvpn[277312]: NOTE: UID/GID downgrade will be delayed because of --client, --pull, or --up-delay
Aug 27 11:14:40 fedora34 nm-openvpn[277312]: [medewerker.surf.eduvpn.nl] Peer Connection Initiated with [AF_INET6][REDACTED]:1194
Aug 27 11:14:40 fedora34 nm-openvpn[277312]: OpenVPN ROUTE: remote_host undefined
Aug 27 11:14:40 fedora34 nm-openvpn[277312]: OpenVPN ROUTE: failed to parse/resolve route for host/network: remote_host
Aug 27 11:14:40 fedora34 nm-openvpn[277312]: TUN/TAP device tun0 opened
Aug 27 11:14:40 fedora34 nm-openvpn[277312]: /usr/libexec/nm-openvpn-service-openvpn-helper --debug 0 277306 --bus-name org.freedesktop.NetworkManager.openvpn.Connection_18 --tun -- tun0 1500 1624 [REDACTED] 255.255.255.192 init
Aug 27 11:14:40 fedora34 NetworkManager[1314]: <info>  [1630055680.3554] manager: (tun0): new Tun device (/org/freedesktop/NetworkManager/Devices/15)
Aug 27 11:14:40 fedora34 NetworkManager[1314]: <info>  [1630055680.3667] vpn-connection[0x5562c6026730,fa728f67-49b5-4671-acf2-b4303789f52b,"eduVPN",0]: VPN connection: (IP Config Get) reply received.
Aug 27 11:14:40 fedora34 NetworkManager[1314]: <info>  [1630055680.3677] vpn-connection[0x5562c6026730,fa728f67-49b5-4671-acf2-b4303789f52b,"eduVPN",12:(tun0)]: VPN connection: (IP4 Config Get) reply received
Aug 27 11:14:40 fedora34 NetworkManager[1314]: <info>  [1630055680.3685] vpn-connection[0x5562c6026730,fa728f67-49b5-4671-acf2-b4303789f52b,"eduVPN",12:(tun0)]: VPN connection: (IP6 Config Get) reply received
Aug 27 11:14:40 fedora34 NetworkManager[1314]: <info>  [1630055680.3692] vpn-connection[0x5562c6026730,fa728f67-49b5-4671-acf2-b4303789f52b,"eduVPN",12:(tun0)]: Data: VPN Gateway: [REDACTED]
Aug 27 11:14:40 fedora34 NetworkManager[1314]: <info>  [1630055680.3692] vpn-connection[0x5562c6026730,fa728f67-49b5-4671-acf2-b4303789f52b,"eduVPN",12:(tun0)]: Data: Tunnel Device: "tun0"
Aug 27 11:14:40 fedora34 NetworkManager[1314]: <info>  [1630055680.3692] vpn-connection[0x5562c6026730,fa728f67-49b5-4671-acf2-b4303789f52b,"eduVPN",12:(tun0)]: Data: IPv4 configuration:
Aug 27 11:14:40 fedora34 NetworkManager[1314]: <info>  [1630055680.3692] vpn-connection[0x5562c6026730,fa728f67-49b5-4671-acf2-b4303789f52b,"eduVPN",12:(tun0)]: Data:   Internal Gateway: [REDACTED]
Aug 27 11:14:40 fedora34 NetworkManager[1314]: <info>  [1630055680.3692] vpn-connection[0x5562c6026730,fa728f67-49b5-4671-acf2-b4303789f52b,"eduVPN",12:(tun0)]: Data:   Internal Address: [REDACTED]
Aug 27 11:14:40 fedora34 NetworkManager[1314]: <info>  [1630055680.3692] vpn-connection[0x5562c6026730,fa728f67-49b5-4671-acf2-b4303789f52b,"eduVPN",12:(tun0)]: Data:   Internal Prefix: 26
Aug 27 11:14:40 fedora34 NetworkManager[1314]: <info>  [1630055680.3694] vpn-connection[0x5562c6026730,fa728f67-49b5-4671-acf2-b4303789f52b,"eduVPN",12:(tun0)]: Data:   Internal Point-to-Point Address: [REDACTED]
Aug 27 11:14:40 fedora34 NetworkManager[1314]: <info>  [1630055680.3694] vpn-connection[0x5562c6026730,fa728f67-49b5-4671-acf2-b4303789f52b,"eduVPN",12:(tun0)]: Data:   Static Route: 0.0.0.0/0   Next Hop: [REDACTED]
Aug 27 11:14:40 fedora34 NetworkManager[1314]: <info>  [1630055680.3694] vpn-connection[0x5562c6026730,fa728f67-49b5-4671-acf2-b4303789f52b,"eduVPN",12:(tun0)]: Data:   Static Route: [REDACTED]/26   Next Hop: 0.0.0.0
Aug 27 11:14:40 fedora34 NetworkManager[1314]: <info>  [1630055680.3694] vpn-connection[0x5562c6026730,fa728f67-49b5-4671-acf2-b4303789f52b,"eduVPN",12:(tun0)]: Data:   Internal DNS: [REDACTED]
Aug 27 11:14:40 fedora34 nm-openvpn[277312]: GID set to nm-openvpn
Aug 27 11:14:40 fedora34 NetworkManager[1314]: <info>  [1630055680.3694] vpn-connection[0x5562c6026730,fa728f67-49b5-4671-acf2-b4303789f52b,"eduVPN",12:(tun0)]: Data:   Internal DNS: [REDACTED]
Aug 27 11:14:40 fedora34 nm-openvpn[277312]: UID set to nm-openvpn
Aug 27 11:14:40 fedora34 NetworkManager[1314]: <info>  [1630055680.3694] vpn-connection[0x5562c6026730,fa728f67-49b5-4671-acf2-b4303789f52b,"eduVPN",12:(tun0)]: Data:   DNS Domain: '(none)'
Aug 27 11:14:40 fedora34 nm-openvpn[277312]: Initialization Sequence Completed
Aug 27 11:14:40 fedora34 NetworkManager[1314]: <info>  [1630055680.3694] vpn-connection[0x5562c6026730,fa728f67-49b5-4671-acf2-b4303789f52b,"eduVPN",12:(tun0)]: Data: IPv6 configuration:
Aug 27 11:14:40 fedora34 NetworkManager[1314]: <info>  [1630055680.3694] vpn-connection[0x5562c6026730,fa728f67-49b5-4671-acf2-b4303789f52b,"eduVPN",12:(tun0)]: Data:   Internal Address: [REDACTED]
Aug 27 11:14:40 fedora34 NetworkManager[1314]: <info>  [1630055680.3695] vpn-connection[0x5562c6026730,fa728f67-49b5-4671-acf2-b4303789f52b,"eduVPN",12:(tun0)]: Data:   Internal Prefix: 112
Aug 27 11:14:40 fedora34 NetworkManager[1314]: <info>  [1630055680.3695] vpn-connection[0x5562c6026730,fa728f67-49b5-4671-acf2-b4303789f52b,"eduVPN",12:(tun0)]: Data:   Internal Point-to-Point Address: [REDACTED]
Aug 27 11:14:40 fedora34 NetworkManager[1314]: <info>  [1630055680.3695] vpn-connection[0x5562c6026730,fa728f67-49b5-4671-acf2-b4303789f52b,"eduVPN",12:(tun0)]: Data:   Static Route: ::/0   Next Hop: ::
Aug 27 11:14:40 fedora34 NetworkManager[1314]: <info>  [1630055680.3695] vpn-connection[0x5562c6026730,fa728f67-49b5-4671-acf2-b4303789f52b,"eduVPN",12:(tun0)]: Data:   Static Route: [REDACTED]/128   Next Hop: ::
Aug 27 11:14:40 fedora34 NetworkManager[1314]: <info>  [1630055680.3695] vpn-connection[0x5562c6026730,fa728f67-49b5-4671-acf2-b4303789f52b,"eduVPN",12:(tun0)]: Data:   Static Route: [REDACTED]/128   Next Hop: ::
Aug 27 11:14:40 fedora34 NetworkManager[1314]: <info>  [1630055680.3695] vpn-connection[0x5562c6026730,fa728f67-49b5-4671-acf2-b4303789f52b,"eduVPN",12:(tun0)]: Data:   Internal DNS: [REDACTED]
Aug 27 11:14:40 fedora34 NetworkManager[1314]: <info>  [1630055680.3695] vpn-connection[0x5562c6026730,fa728f67-49b5-4671-acf2-b4303789f52b,"eduVPN",12:(tun0)]: Data:   Internal DNS: [REDACTED]
Aug 27 11:14:40 fedora34 NetworkManager[1314]: <info>  [1630055680.3695] vpn-connection[0x5562c6026730,fa728f67-49b5-4671-acf2-b4303789f52b,"eduVPN",12:(tun0)]: Data:   DNS Domain: '(none)'
Aug 27 11:14:40 fedora34 NetworkManager[1314]: <info>  [1630055680.3697] vpn-connection[0x5562c6026730,fa728f67-49b5-4671-acf2-b4303789f52b,"eduVPN",12:(tun0)]: VPN plugin: state changed: started (4)
Aug 27 11:14:40 fedora34 NetworkManager[1314]: <info>  [1630055680.4030] vpn-connection[0x5562c6026730,fa728f67-49b5-4671-acf2-b4303789f52b,"eduVPN",12:(tun0)]: VPN connection: (IP Config Get) complete
Aug 27 11:14:40 fedora34 NetworkManager[1314]: <info>  [1630055680.4042] device (tun0): state change: unmanaged -> unavailable (reason 'connection-assumed', sys-iface-state: 'external')
Aug 27 11:14:40 fedora34 NetworkManager[1314]: <info>  [1630055680.4070] policy: set 'eduVPN' (tun0) as default for IPv4 routing and DNS
Aug 27 11:14:40 fedora34 NetworkManager[1314]: <info>  [1630055680.4074] policy: set 'eduVPN' (tun0) as default for IPv6 routing and DNS
Aug 27 11:14:40 fedora34 NetworkManager[1314]: <info>  [1630055680.4126] device (tun0): state change: unavailable -> disconnected (reason 'connection-assumed', sys-iface-state: 'external')
Aug 27 11:14:40 fedora34 NetworkManager[1314]: <info>  [1630055680.4136] device (tun0): Activation: starting connection 'tun0' (f4e8d08b-44c7-493c-ac5b-3371487fcd17)
Aug 27 11:14:40 fedora34 NetworkManager[1314]: <info>  [1630055680.4143] device (tun0): state change: disconnected -> prepare (reason 'none', sys-iface-state: 'external')
Aug 27 11:14:40 fedora34 NetworkManager[1314]: <info>  [1630055680.4146] device (tun0): state change: prepare -> config (reason 'none', sys-iface-state: 'external')
Aug 27 11:14:40 fedora34 NetworkManager[1314]: <info>  [1630055680.4150] device (tun0): state change: config -> ip-config (reason 'none', sys-iface-state: 'external')
Aug 27 11:14:40 fedora34 NetworkManager[1314]: <info>  [1630055680.4153] device (tun0): state change: ip-config -> ip-check (reason 'none', sys-iface-state: 'external')
Aug 27 11:14:40 fedora34 NetworkManager[1314]: <info>  [1630055680.4150] device (tun0): state change: config -> ip-config (reason 'none', sys-iface-state: 'external')
Aug 27 11:14:40 fedora34 NetworkManager[1314]: <info>  [1630055680.4153] device (tun0): state change: ip-config -> ip-check (reason 'none', sys-iface-state: 'external')
Aug 27 11:14:40 fedora34 NetworkManager[1314]: <info>  [1630055680.4282] device (tun0): state change: ip-check -> secondaries (reason 'none', sys-iface-state: 'external')
Aug 27 11:14:40 fedora34 NetworkManager[1314]: <info>  [1630055680.4286] device (tun0): state change: secondaries -> activated (reason 'none', sys-iface-state: 'external')
```

## Do you have a problem during connecting?

The expected outcome is that all routes that are pushed by the server are added to the routing table. This does not happen:

```
$ route -n | grep tun0
0.0.0.0         [REDACTED]  0.0.0.0         UG    50     0        0 tun0
[REDACTED]  0.0.0.0         255.255.255.192 U     50     0        0 tun0
```

I've inspected the logs and it seems to break because of this:

```
Aug 27 11:14:40 fedora34 nm-openvpn[277312]: OpenVPN ROUTE: remote_host undefined
Aug 27 11:14:40 fedora34 nm-openvpn[277312]: OpenVPN ROUTE: failed to parse/resolve route for host/network: remote_host
```

I don't know why this happens, but it might have to with the fact that the routes are pushed before the connection is established, so the aliases are not resolvable yet. Somehow NetworkManager (which is being used by eduVPN) seems to break when this error is encountered and doesn't add all the other routes. At least that's my gut feeling based on the output in the logs. NetworkManager has no issues with other OpenVPN profiles/servers, among which the one that my institute provides as an alternative to eduVPN, which adds routes just fine.

## Workaround

The routes (minus the bogus route with the `remote_host` alias) are added correctly if I download an eduVPN profile and connect with `sudo openvpn --config <config.ovpn>`. It still prints an error, but it seems that the invalid route just get ignored instead of breaking all other routes:

```
2021-08-25 09:55:30 OpenVPN ROUTE: remote_host undefined
2021-08-25 09:55:30 OpenVPN ROUTE: failed to parse/resolve route for host/network: remote_host
...
2021-08-25 09:55:30 sitnl_send: rtnl: generic error (-22): Invalid argument
2021-08-25 09:55:30 ERROR: Linux route add command failed
```

Outcome of workaround:

```
$ route -n | grep tun0 | wc -l
94
```

**Comment by fkooman** [comment] 2021-08-30 14:20
> 2021-08-25 09:55:30 OpenVPN ROUTE: remote_host undefined
> 2021-08-25 09:55:30 OpenVPN ROUTE: failed to parse/resolve route for host/network: remote_host

These happen because you connect over IPv6 to the VPN server. I see the same thing here with my test server, but as you already found, they are not "fatal".

I'm testing with routes being push. What I can see so far is that IPv6 works fine (in split tunnel scenario), but IPv4 does *not*.

**Comment by fkooman** [comment] 2021-08-30 14:28
When removing this line from the server configuration everything works fine on Fedora 34. Both IPv4 and IPv6 routes are properly configured and work. **With** this line enabled only IPv6 works. The IPv4 traffic is NOT going through the tunnel.

**Comment by fkooman** [comment] 2021-08-30 14:31
I tested this by importing the VPN configuration file directly in NetworkManager using GNOME Settings and setting the checkbox from the screenshot:

![image](https://user-images.githubusercontent.com/616885/131355628-e1589235-d3ae-4709-9b7f-5890007a8faf.png)

**Comment by fkooman** [comment] 2021-08-30 14:37
Seeing the same behavior on Debian 11 client (OpenVPN 2.5.1). Fedora 34 has OpenVPN 2.5.3. It wouldn't surprise me that OpenVPN 2.4, e.g. on Debian 10 (still) work fine, but I don't have a Debian 10 box with native IPv6 to confirm this.

**Comment by fkooman** [comment] 2021-08-30 14:39
A working workaround is changing the `remote` line in the client configuration (or GNOME Settings GUI) to point directly to the IPv4 address. Then everything works again as expected...

**Comment by fkooman** [comment] 2021-08-30 14:47
It only seems to break NetworkManager...when going through the cli using sudo openvpn it *does* work. So perhaps NetworkManager does something special these days? May have something to do with using netlink to configure OpenVPN routes (new in OpenVPN 2.5).

**Comment by martijnkruiten** [comment] 2021-09-21 07:44
I've put the VPN server domains in `/etc/hosts` with their IPv4 address as a temporary workaround. The only issue that still remains is that each time that the profile is renewed, all traffic is routed over the VPN by default. Is it possible for eduVPN to tell NetworkManager to only use the exported routes by default (and match the default behavior of the MacOS and Windows clients)? I now have to do this manually each time. Of course the IPv6 bug needs to be fixed first for this to work reliably.

**Comment by fkooman** [comment] 2021-09-21 07:49
> I've put the VPN server domains in `/etc/hosts` with their IPv4 address as a temporary workaround. The only issue that still remains is that each time that the profile is renewed, all traffic is routed over the VPN by default. Is it possible for eduVPN to tell NetworkManager to only use the exported routes by default (and match the default behavior of the MacOS and Windows clients)? I now have to do this manually each time. Of course the IPv6 bug needs to be fixed first for this to work reliably.

Yes, that is possible. We have an open issue regarding this: #167.

**Comment by burgerga** [comment] 2021-10-19 07:39
Maybe you can throw your weight to this issue https://gitlab.gnome.org/GNOME/NetworkManager-openvpn/-/issues/48
Because it is indeed NetworkManager specific to add this default route

**Comment by alvra** [comment] 2021-11-08 12:42
@fkooman Is there anything this client can do to solve the issue?

**Comment by fkooman** [comment] 2021-11-08 12:48
> @fkooman Is there anything this client can do to solve the issue?

Yes, it would require understanding the problem exactly and probably submitting patches to OpenVPN and/or NetworkManager.

**Comment by gijzelaerr** [comment] 2021-11-08 16:50
Ok then this is ongoing work and should not block the 2.2 release.

**Comment by fkooman** [comment] 2021-12-02 11:36
I spent a lot of time on trying to fix it, but I can't find the root cause. So closing this as "unsolvable". If anyone has the complete solution that works and doesn't break other platforms feel free to provide it.

**Closed by fkooman** 2021-12-02 11:36 UTC

**Comment by martijnkruiten** [comment] 2021-12-02 12:10
Does that mean that https://github.com/eduvpn/vpn-server-node/issues/51 is not going to be used? That's at least a partial fix/workaround, right?

**Comment by fkooman** [comment] 2021-12-02 12:26
> Does that mean that [eduvpn/vpn-server-node#51](https://github.com/eduvpn/vpn-server-node/issues/51) is not going to be used? That's at least a partial fix/workaround, right?

Yes, that one has already been implemented and part of the latest release.

The case that currently does *not* work:

1. Linux client
2. Split tunnel configuration
3. Connect over IPv6
4. Pushed IPv4 routes contain the public IPv4 address of the VPN server

What was fixed as part of https://github.com/eduvpn/vpn-server-node/issues/51 is that it now works properly for the case where there is _no_ overlap.

**Comment by martijnkruiten** [comment] 2021-12-02 12:29
I see, that's good news for us (no overlap), but not a complete fix for all situations. I misinterpreted your statement and thought that you didn't want to apply the fix that you already had.

**Comment by fkooman** [comment] 2021-12-02 12:30
Sorry for the confusion! The no-overlap case has been fixed. In case overlap is detected the `vpn-maint-apply-changes` script that is run to update the server will also show a warning, e.g.:

```
WARNING: IPv4 address(es) associated with hostName [116.203.195.80] will *also* be pushed to VPN clients using "routes". This MAY result in connectivity problems!
```

**Comment by gvde** [comment] 2023-01-12 10:10
@fkooman I am running into this issue in the overlap case on our v2 installation. Has this been fixed in v3 for the overlap case?

If I remove 
```
push "route remote_host 255.255.255.255 net_gateway"
```
from the openvpn server configuration, it'll work fine for Ubuntu 22.04 and other Linux version connecting via IPv4 or IPv6. The client will automatically set the route to connect to the server directly.

However, then my Windows clients won't work anymore if they connect via IPv4.

**Comment by fkooman** [comment] 2023-01-12 11:46
> @fkooman I am running into this issue in the overlap case on our v2 installation. Has this been fixed in v3 for the overlap case?

I'm not sure. I don't remember doing anything regarding this issue...

I'd recommend simply not having any overlap, or looking at using WireGuard together with 3.x eduVPN server, there it may not even be a problem...

**Comment by gvde** [comment] 2023-01-12 13:01
> I'd recommend simply not having any overlap, or looking at using WireGuard together with 3.x eduVPN server, there it may not even be a problem...

Well, avoiding overlap is messy: excluding a single IP address from a network results in an exponential increase of pushed routes by size of network. I suppose, the correct solution would be not to push that route but fix this on the client side: the client should always push a direct route to the vpn server. I cannot really see why it shouldn't. For Linux/openvpn this already seems to be the case. The Windows eduvpn client via IPv4 doesn't do it...
