### ISSUE TITLE
press enter after entering custom URL should start authorization

### ISSUE THREAD

**Issue by fkooman** [eduvpn/python-eduvpn-client#127] opened 2018-07-05 13:31 UTC
now Enter doesn't work.

**Comment by gijzelaerr** [comment] 2018-07-05 15:18
duplicate of https://github.com/eduvpn/python-eduvpn-client/issues/117, but description is better now.

**Comment by gijzelaerr** [comment] 2018-07-26 11:34
this is also an issue for the totp and yubi input field

**Closed** 2018-07-26 11:35 UTC
Labels: enhancement, low priority
