### ISSUE TITLE
Fedora 38 SELinux problems

### ISSUE THREAD

**Issue by donttouchthis** [eduvpn/python-eduvpn-client#554] opened 2023-10-17 12:20 UTC
# Installation

Fedora package eduvpn-client-4.1.3-1.fc38.noarch

# Version

4.1.3

# Check if your issue is in the known issues list
# OS/Distribution

Fedora 38 (x86_64)

# Logs

## Do you have a problem while adding before connecting?

The connection works

## Do you have a problem during or after connecting?

With SELinux enabled: When the connection is established Gnome-desktop freezes when opening the Activities.

```
SELinux is preventing ModemManager from using the execmem access on a process.

*****  Plugin allow_execmem (91.4 confidence) suggests   *********************

If this issue occurred during normal system operation.
Then this alert could be a serious issue and your system could be compromised.
Do
contact your security administrator and report this issue

*****  Plugin catchall (9.59 confidence) suggests   **************************

If you believe that ModemManager should be allowed execmem access on processes labeled modemmanager_t by default.
Then you should report this as a bug.
You can generate a local policy module to allow this access.
Do
allow this access for now by executing:
# ausearch -c 'ModemManager' --raw | audit2allow -M my-ModemManager
# semodule -X 300 -i my-ModemManager.pp


Additional Information:
Source Context                system_u:system_r:modemmanager_t:s0
Target Context                system_u:system_r:modemmanager_t:s0
Target Objects                Unknown [ process ]
Source                        ModemManager
Source Path                   ModemManager
Port                          <Unknown>
Host                          some-mob.some-where.de
Source RPM Packages           
Target RPM Packages           
SELinux Policy RPM            selinux-policy-targeted-38.29-1.fc38.noarch
Local Policy RPM              selinux-policy-targeted-38.29-1.fc38.noarch
Selinux Enabled               True
Policy Type                   targeted
Enforcing Mode                Enforcing
Host Name                     some-mob.some-where.de
Platform                      Linux some-mob.some-where.de
                              6.5.6-200.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Fri
                              Oct  6 19:02:35 UTC 2023 x86_64
Alert Count                   3
First Seen                    2023-10-17 12:30:58 CEST
Last Seen                     2023-10-17 13:23:31 CEST
Local ID                      f7c288c8-b269-42a3-9f60-918e9408ae42

Raw Audit Messages
type=AVC msg=audit(1697541811.116:144): avc:  denied  { execmem } for  pid=1004 comm="ModemManager" scontext=system_u:system_r:modemmanager_t:s0 tcontext=system_u:system_r:modemmanager_t:s0 tclass=process permissive=0

Hash: ModemManager,modemmanager_t,modemmanager_t,process,execmem

```

**Comment by jwijenbergh** [comment] 2023-10-17 19:31
Hi! Thanks for making the issue.

Could you let me know if it is also a problem when importing a VPN manually with NetworkManager:

For OpenVPN:
```
nmcli connection import type openvpn file /path/to/eduvpn.ovpn```

For WireGuard

```
nmcli connection import type wireguard file /path/to/eduvpn.conf
```

You can download an OpenVPN or WireGuard file from the eduVPN portal of your organization.

Does this issue only happen when the client is opened and connected or does the issue go away when the VPN is connected but the client is closed?

Next, does it only happen with SELinux enabled? I need as much information as possible to find out if this is a client bug or NetworkManager/ModemManager/something else bug.

Thanks

**Comment by jwijenbergh** [comment] 2023-10-19 14:07
Ok understood. If you feel confident it's not a client bug you may wish to close the issue. Otherwise we will leave this open and let me know once you have a good way reproduce it again

**Comment by jwijenbergh** [comment] 2023-10-30 13:03
Closing due to inactivity

**Closed by jwijenbergh** 2023-10-30 13:03 UTC
