### ISSUE TITLE
can't enable connection

### ISSUE THREAD

**Issue by fkooman** [eduvpn/python-eduvpn-client#110] opened 2018-05-25 15:14 UTC
![image](https://user-images.githubusercontent.com/616885/40552054-f4c2ca4a-603e-11e8-94f2-e45a48f11ac1.png)

```
2018-05-25 17:13:01,665 - ERROR - eduvpn.actions.activate - metadata for 979cad9e-114b-4743-ab21-950be33a30f1 doesn't contain oauth2 token
2018-05-25 17:13:01,666 - INFO - eduvpn.manager - connecting profile with uuid 979cad9e-114b-4743-ab21-950be33a30f1 using NetworkManager
2018-05-25 17:13:01,667 - ERROR - eduvpn.util - can't enable connection: EduvpnException: org.freedesktop.NetworkManager.Settings.InvalidConnection: No connection with the UUID was found.
Traceback (most recent call last):
  File "/home/fkooman/.local/lib/python3.6/site-packages/eduvpn/manager.py", line 137, in connect_provider
    connection = NetworkManager.Settings.GetConnectionByUuid(uuid)
  File "<string>", line 4, in GetConnectionByUuid
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.NetworkManager.Settings.InvalidConnection: No connection with the UUID was found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fkooman/.local/lib/python3.6/site-packages/eduvpn/ui.py", line 87, in switched
    switched(meta=self.selected_meta, builder=self.builder)
  File "/home/fkooman/.local/lib/python3.6/site-packages/eduvpn/actions/switch.py", line 25, in switched
    activate_connection(meta=meta, builder=builder)
  File "/home/fkooman/.local/lib/python3.6/site-packages/eduvpn/actions/activate.py", line 38, in activate_connection
    connect_provider(meta.uuid)
  File "/home/fkooman/.local/lib/python3.6/site-packages/eduvpn/manager.py", line 140, in connect_provider
    raise EduvpnException(e)
eduvpn.exceptions.EduvpnException: org.freedesktop.NetworkManager.Settings.InvalidConnection: No connection with the UUID was found.
2018-05-25 17:13:06,697 - INFO - eduvpn.actions.switch - switch activated, old state False
2018-05-25 17:13:06,697 - INFO - eduvpn.actions.switch - setting switch ON
2018-05-25 17:13:06,697 - INFO - eduvpn.actions.activate - Connecting to 979cad9e-114b-4743-ab21-950be33a30f1
2018-05-25 17:13:07,084 - ERROR - eduvpn.actions.activate - metadata for 979cad9e-114b-4743-ab21-950be33a30f1 doesn't contain oauth2 token
2018-05-25 17:13:07,084 - INFO - eduvpn.manager - connecting profile with uuid 979cad9e-114b-4743-ab21-950be33a30f1 using NetworkManager
2018-05-25 17:13:07,085 - ERROR - eduvpn.util - can't enable connection: EduvpnException: org.freedesktop.NetworkManager.Settings.InvalidConnection: No connection with the UUID was found.
```

**Comment by gijzelaerr** [comment] 2018-06-22 14:50
also looks like a race condition that is very hard to reproduce. There is suttle bug somewhere where the profile is being updated while the user interface is switching profiles.

**Comment by gijzelaerr** [comment] 2018-06-29 12:36
closing for now, i can't replicate the issue but this was the only point where i can come up with where you would be able to active a profile by UUID while it doesn't exists.

**Closed by gijzelaerr** 2018-06-29 12:36 UTC
Labels: bug
